from abc import ABC, abstractmethod
from uuid import UUID

from app.models.domain import FrozenStudyExport, Session, StudyLifecycle, StudyRecord, User


class Repository(ABC):
    @abstractmethod
    async def initialize(self) -> None: ...
    @abstractmethod
    async def create_user(self, user: User) -> User: ...
    @abstractmethod
    async def get_user_by_email(self, email: str) -> User | None: ...
    @abstractmethod
    async def get_user(self, user_id: UUID) -> User | None: ...
    @abstractmethod
    async def list_users(self) -> list[User]: ...
    @abstractmethod
    async def save_user(self, user: User) -> User: ...
    @abstractmethod
    async def delete_user(self, user_id: UUID) -> None: ...
    @abstractmethod
    async def save_session(self, session: Session) -> Session: ...
    @abstractmethod
    async def get_session(self, session_id: UUID, user_id: UUID) -> Session | None: ...
    @abstractmethod
    async def list_sessions(self, user_id: UUID) -> list[Session]: ...
    @abstractmethod
    async def delete_session(self, session_id: UUID, user_id: UUID) -> bool: ...
    @abstractmethod
    async def save_study_record(self, record: StudyRecord) -> StudyRecord: ...
    @abstractmethod
    async def list_study_records(self, user_id: UUID | None = None) -> list[StudyRecord]: ...
    @abstractmethod
    async def delete_study_records(self, user_id: UUID) -> int: ...
    @abstractmethod
    async def get_study_lifecycle(self, protocol_version: str) -> StudyLifecycle | None: ...
    @abstractmethod
    async def save_study_lifecycle(self, lifecycle: StudyLifecycle) -> StudyLifecycle: ...
    @abstractmethod
    async def save_frozen_export(self, export: FrozenStudyExport) -> FrozenStudyExport: ...
    @abstractmethod
    async def get_frozen_export(self, export_id: UUID) -> FrozenStudyExport | None: ...
    @abstractmethod
    async def begin_dataset_freeze(self, protocol_version: str, token: UUID) -> StudyLifecycle | None: ...
    @abstractmethod
    async def complete_dataset_freeze(self, export: FrozenStudyExport, token: UUID) -> StudyLifecycle: ...
    @abstractmethod
    async def abort_dataset_freeze(self, protocol_version: str, token: UUID) -> None: ...
    @abstractmethod
    async def store_refresh_token(self, token_id: str, user_id: UUID, digest: str, expires_at) -> None: ...
    @abstractmethod
    async def rotate_refresh_token(self, token_id: str, digest: str) -> UUID | None: ...
    @abstractmethod
    async def revoke_user_tokens(self, user_id: UUID) -> None: ...
    @abstractmethod
    async def store_email_verification_token(self, user_id: UUID, digest: str, expires_at) -> None: ...
    @abstractmethod
    async def consume_email_verification_token(self, digest: str) -> UUID | None: ...
    @abstractmethod
    async def store_password_reset_token(self, user_id: UUID, digest: str, expires_at) -> None: ...
    @abstractmethod
    async def consume_password_reset_token(self, digest: str) -> UUID | None: ...
    @abstractmethod
    async def mark_email_verified(self, user_id: UUID) -> User | None: ...
