from abc import ABC, abstractmethod
from uuid import UUID

from app.models.domain import Session, User


class Repository(ABC):
    @abstractmethod
    async def initialize(self) -> None: ...
    @abstractmethod
    async def create_user(self, user: User) -> User: ...
    @abstractmethod
    async def get_user_by_email(self, email: str) -> User | None: ...
    @abstractmethod
    async def get_user(self, user_id: UUID) -> User | None: ...
    @abstractmethod
    async def delete_user(self, user_id: UUID) -> None: ...
    @abstractmethod
    async def save_session(self, session: Session) -> Session: ...
    @abstractmethod
    async def get_session(self, session_id: UUID, user_id: UUID) -> Session | None: ...
    @abstractmethod
    async def list_sessions(self, user_id: UUID) -> list[Session]: ...
    @abstractmethod
    async def delete_session(self, session_id: UUID, user_id: UUID) -> bool: ...
    @abstractmethod
    async def store_refresh_token(self, token_id: str, user_id: UUID, digest: str, expires_at) -> None: ...
    @abstractmethod
    async def rotate_refresh_token(self, token_id: str, digest: str) -> UUID | None: ...
    @abstractmethod
    async def revoke_user_tokens(self, user_id: UUID) -> None: ...
    @abstractmethod
    async def store_email_verification_token(self, user_id: UUID, digest: str, expires_at) -> None: ...
    @abstractmethod
    async def consume_email_verification_token(self, digest: str) -> UUID | None: ...
    @abstractmethod
    async def mark_email_verified(self, user_id: UUID) -> User | None: ...
