import { useEffect, useRef, useState } from 'react'
import { api } from '../services/api'
import type { ActionCard as Card } from '../types/api'

const fields={opening_sentence:'Opening sentence',main_request:'Main request',boundary_or_fallback:'Boundary or fallback',reminder:'One reminder'} as const
type Wording=Pick<Card,keyof typeof fields>

export function ActionCard({sessionId,onVersion}:{sessionId:string;onVersion:(version:number)=>void}) {
  const mounted=useRef(true)
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
  const [card,setCard]=useState<Wording|null>(null),[version,setVersion]=useState(0),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0)
  useEffect(()=>{let active=true;void api.getActionCard(sessionId).then(result=>{if(active){setCard(result.card);setVersion(result.version);setSaved(result.saved);setError('')}}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:'Your action card could not be loaded.')});return()=>{active=false}},[sessionId,retry])
  async function save(){if(!card)return;setBusy(true);setError('');setNotice('');try{const wording=Object.fromEntries(Object.keys(fields).map(key=>[key,card[key as keyof Wording]])) as Wording;const result=await api.saveActionCard(sessionId,version,wording);if(!mounted.current)return;setVersion(result.version);onVersion(result.version);setSaved(true);setNotice('Action card saved.')}catch(caught){setError(caught instanceof Error?caught.message:'The card could not be saved. Your edits are kept.')}finally{setBusy(false)}}
  async function refreshVersion(){setBusy(true);try{const result=await api.getActionCard(sessionId);if(!mounted.current)return;setVersion(result.version);onVersion(result.version);setError('');setNotice('Saved version refreshed. Your draft is kept; saving will replace the current saved card.')}catch{setError('Could not refresh the saved version. Your draft is kept.')}finally{setBusy(false)}}
  function text(){return `My conversation action card\nDraft wording for review, not an agreed commitment.\n\n${Object.entries(fields).map(([key,label])=>`${label}\n${card?.[key as keyof Wording]??''}`).join('\n\n')}`}
  async function copy(){try{await navigator.clipboard.writeText(text());setNotice('Action card copied.')}catch{setError('Clipboard access was unavailable. Download the text or select and copy the fields.')}}
  function download(){const url=URL.createObjectURL(new Blob([text()],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='conversation-action-card.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Action card downloaded.')}
  if(!card)return <section aria-label="Action card">{error?<><p role="alert">{error}</p><button onClick={()=>{setError('');setRetry(value=>value+1)}}>Retry loading action card</button></>:<p role="status">Preparing your action card…</p>}</section>
  return <section className="action-card" aria-label="Action card"><h2>Your plan for the real conversation</h2><p>{saved?'Your saved wording.':'Template suggestions based on your rehearsal and chosen objective.'} Edit every line to make it yours. These are suggestions, not promises or commitments made by the other person.</p><p>Saved separately from feedback and scores. Copy and download include your current edits, even before saving.</p><fieldset disabled={busy}><legend>Words to take with you</legend>{Object.entries(fields).map(([key,label])=><div key={key}><label htmlFor={`card-${key}`}>{label}</label><textarea id={`card-${key}`} maxLength={key==='reminder'?300:500} value={card[key as keyof Wording]} onChange={event=>{setCard({...card,[key]:event.target.value});setSaved(false);setNotice('')}}/></div>)}</fieldset><button disabled={busy||Object.keys(fields).some(key=>!card[key as keyof Wording].trim())} onClick={()=>void save()}>{busy?'Saving…':'Save action card'}</button><button disabled={busy} onClick={()=>void copy()}>Copy text</button><button disabled={busy} onClick={download}>Download text</button>{notice&&<p role="status">{notice}</p>}{error&&<><p role="alert" className="error">{error}</p><button disabled={busy} onClick={()=>void refreshVersion()}>Refresh saved version and keep my draft</button></>}</section>
}
