import { useEffect, useMemo, useState } from 'react'
import { goalLabel, recommendedScenario } from '../practiceGoals'
import { api } from '../services/api'
import type { SessionSummary, UserProfile } from '../types/api'

function relativeDate(value:string) { const days=Math.floor((Date.now()-new Date(value).getTime())/86_400_000);if(days<=0)return'Today';if(days===1)return'Yesterday';if(days<7)return`${days} days ago`;return new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short'}) }

export function HomeDashboard({user,onPractice,onSettings,onHome,onLogout}:{user:UserProfile;onPractice:(sessionId?:string,roleplay?:boolean)=>void;onSettings:()=>void;onHome:()=>void;onLogout:()=>void}) {
  const [sessions,setSessions]=useState<SessionSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<string>(),[title,setTitle]=useState('')
  useEffect(()=>{let active=true;void api.listSessions().then(value=>active&&setSessions(value)).catch(()=>active&&setError('Your history could not be loaded.')).finally(()=>active&&setLoading(false));return()=>{active=false}},[])
  const completed=sessions.filter(session=>session.feedback)
  const metrics=useMemo(()=>{const values=new Map<string,number[]>();completed.forEach(session=>session.feedback?.metrics.forEach(metric=>values.set(metric.name,[...(values.get(metric.name)??[]),metric.score])));return[...values].map(([name,scores])=>({name,score:scores.reduce((sum,value)=>sum+value,0)/scores.length})).sort((a,b)=>b.score-a.score).slice(0,4)},[completed])
  async function saveTitle(id:string){if(!title.trim())return;const updated=await api.renameSession(id,title);setSessions(current=>current.map(session=>session.session_id===id?updated:session));setEditing(undefined)}
  async function remove(id:string){if(!confirm('Delete this session permanently?'))return;await api.deleteSession(id);setSessions(current=>current.filter(session=>session.session_id!==id))}
  const name=user.preferred_name||user.first_name||'there',recommendation=recommendedScenario(user.practice_goals)
  return <main className="home-dashboard"><header><button className="brand-link" onClick={onHome}><span className="brand-mark">A</span><span className="brand">AffectLab</span></button><div className="header-actions"><span>{name}</span><button className="text-button" onClick={onSettings}>Settings</button><button className="text-button" onClick={async()=>{await api.logout();onLogout()}}>Sign out</button></div></header>
    <section className="home-welcome"><div><p className="eyebrow">Your practice space</p><h1>Welcome back, {name}.</h1><p>Reflect on what is happening, rehearse the words, or continue where you left off.</p></div><div className="home-actions"><button className="primary" onClick={()=>onPractice(undefined,false)}>Start a reflection</button><button className="secondary" onClick={()=>onPractice(undefined,true)}>Start a role-play</button></div></section>
    <section className="home-overview"><article className="focus-card"><p className="eyebrow">Current focus</p><h2>{user.practice_goals.length?user.practice_goals.map(goalLabel).join(' · '):'Choose a practice goal'}</h2><p>Recommended: <strong>{recommendation.replaceAll('_',' ')}</strong>.</p><button onClick={()=>onPractice(undefined,true)}>Practise this focus →</button></article><article className="stat-card"><strong>{completed.length}</strong><span>rehearsals completed</span></article><article className="stat-card"><strong>{sessions.length}</strong><span>saved sessions</span></article></section>
    <div className="history-layout"><section className="session-history"><div className="section-heading"><p className="eyebrow">Recent activity</p><h2>Continue your work</h2></div>{loading?<p>Loading your sessions…</p>:error?<p className="error" role="alert">{error}</p>:sessions.length===0?<div className="history-empty"><span>✦</span><h3>Your first session starts here.</h3><p>Use reflection to explore a situation, or begin a guided rehearsal.</p></div>:<div className="history-list">{sessions.map(session=><article key={session.session_id}><button className="session-main" onClick={()=>onPractice(session.session_id)}><span className={`session-kind ${session.roleplay?'roleplay':'reflection'}`}>{session.roleplay?'R':'✦'}</span><span><strong>{session.title}</strong><small>{relativeDate(session.updated_at)} · {session.turn_count} turns{session.roleplay?` · ${session.roleplay.difficulty_level}`:''}</small></span><em>{session.feedback?'Completed':session.roleplay?.status==='paused'?'Paused':'Continue'}</em></button><div className="session-menu">{editing===session.session_id?<form onSubmit={event=>{event.preventDefault();void saveTitle(session.session_id)}}><input maxLength={80} value={title} onChange={event=>setTitle(event.target.value)} autoFocus aria-label="Session title"/><button>Save</button><button type="button" onClick={()=>setEditing(undefined)}>Cancel</button></form>:<><button onClick={()=>{setEditing(session.session_id);setTitle(session.title)}}>Rename</button><button className="delete" onClick={()=>void remove(session.session_id)}>Delete</button></>}</div></article>)}</div>}</section>
      <aside className="progress-history"><p className="eyebrow">Practice history</p><h2>Skills observed</h2>{metrics.length?<><p>Average evidence scores across {completed.length} completed rehearsal{completed.length===1?'':'s'}.</p><div>{metrics.map(metric=><article key={metric.name}><span><strong>{metric.name.replaceAll('_',' ')}</strong><small>{Math.round(metric.score*100)}%</small></span><i><b style={{width:`${metric.score*100}%`}}/></i></article>)}</div><small className="progress-note">Communication features observed in rehearsals, not a clinical assessment.</small></>:<div className="progress-empty"><p>Complete a role-play to begin building an evidence-based practice history.</p><button onClick={()=>onPractice(undefined,true)}>Choose a scenario</button></div>}</aside></div>
  </main>
}
