import { useEffect, useRef, useState } from 'react'
import { PRACTICE_GOALS } from '../practiceGoals'
import { api } from '../services/api'
import type { UserProfile } from '../types/api'

const totalSteps = 4

export function Onboarding({user, onComplete, onSignOut}: {user:UserProfile;onComplete:(user:UserProfile)=>void;onSignOut:()=>void}) {
  const [step, setStep] = useState(0)
  const [goals, setGoals] = useState<string[]>(user.practice_goals)
  const [microphone, setMicrophone] = useState(localStorage.getItem('affectlab_microphone_enabled') !== 'false')
  const [busy, setBusy] = useState(false), [error, setError] = useState('')
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => heading.current?.focus(), [step])
  function toggleGoal(id:string) { setGoals(current => current.includes(id) ? current.filter(goal => goal !== id) : current.length < 3 ? [...current,id] : current) }
  async function finish() { if (!goals.length) { setError('Choose at least one practice goal.'); return } setBusy(true); setError(''); try { localStorage.setItem('affectlab_microphone_enabled', String(microphone)); onComplete(await api.completeOnboarding(goals)) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Onboarding could not be saved.') } finally { setBusy(false) } }
  return <main className="onboarding-shell"><header><span><span className="brand-mark">A</span><span className="brand">AffectLab</span></span><button className="text-button" onClick={async()=>{await api.logout();onSignOut()}}>Sign out</button></header><section className="onboarding-card"><div className="onboarding-progress" aria-label={`Step ${step+1} of ${totalSteps}`}>{Array.from({length:totalSteps},(_,index)=><i key={index} className={index<=step?'active':''}/>)}</div>
    {step===0&&<div className="onboarding-step"><p className="eyebrow">Welcome to AffectLab</p><h1 ref={heading} tabIndex={-1}>Practise at your own pace.</h1><p>AffectLab helps you prepare for difficult conversations through reflection, guided rehearsal, and evidence-based feedback. You decide what to share and when to stop.</p><div className="onboarding-feature-grid"><article><strong>Reflect</strong><span>Untangle the situation and decide what you need.</span></article><article><strong>Rehearse</strong><span>Practise with an adaptive conversation partner.</span></article><article><strong>Review</strong><span>See communication evidence—not personality judgements.</span></article></div></div>}
    {step===1&&<div className="onboarding-step"><p className="eyebrow">Signals, not certainty</p><h1 ref={heading} tabIndex={-1}>You are the authority on how you feel.</h1><p>Text and voice estimates can be wrong. AffectLab uses them as tentative signals to adjust pacing, never as diagnoses or facts about you.</p><div className="boundary-list"><article><span>01</span><div><strong>Safety comes first</strong><p>Text-based crisis safeguards take precedence over model predictions and role-play.</p></div></article><article><span>02</span><div><strong>No medical claims</strong><p>This is a research rehearsal tool, not therapy, diagnosis, or emergency care.</p></div></article><article><span>03</span><div><strong>You stay in control</strong><p>Pause, finish, edit, delete, or avoid voice input whenever you choose.</p></div></article></div></div>}
    {step===2&&<div className="onboarding-step"><p className="eyebrow">Voice and privacy</p><h1 ref={heading} tabIndex={-1}>Voice is always optional.</h1><p>When enabled, a recording may be sent to OpenAI for transcription and processed in memory by the local affect model. AffectLab does not save the recording.</p><label className="onboarding-toggle"><span><strong>Enable voice input</strong><small>You still press Add voice before every recording.</small></span><input type="checkbox" checked={microphone} onChange={event=>setMicrophone(event.target.checked)}/></label><p className="onboarding-note">Conversation text is stored locally for up to 30 days and may be sent to OpenAI when configured, as described during registration.</p></div>}
    {step===3&&<div className="onboarding-step"><p className="eyebrow">Personalise your practice</p><h1 ref={heading} tabIndex={-1}>What would you like to work on?</h1><p>Choose one to three goals. We will use them to recommend a starting rehearsal; you can still access every scenario.</p><div className="goal-grid">{PRACTICE_GOALS.map(goal=><button key={goal.id} className={goals.includes(goal.id)?'selected':''} aria-pressed={goals.includes(goal.id)} onClick={()=>toggleGoal(goal.id)}><span>{goals.includes(goal.id)?'✓':'+'}</span><div><strong>{goal.label}</strong><small>{goal.description}</small></div></button>)}</div>{goals.length===3&&<p className="goal-limit" role="status">Three goals selected. Remove one to choose another.</p>}</div>}
    {error&&<p className="error" role="alert">{error}</p>}<div className="onboarding-actions">{step>0&&<button className="secondary" onClick={()=>setStep(current=>current-1)}>Back</button>}<span>Step {step+1} of {totalSteps}</span>{step<totalSteps-1?<button className="primary" onClick={()=>setStep(current=>current+1)}>Continue</button>:<button className="primary" disabled={busy||!goals.length} onClick={()=>void finish()}>{busy?'Saving…':'Start practising'}</button>}</div></section></main>
}
