import { useEffect, useState } from 'react'
import { api } from '../services/api'
import type { ResearchDashboardData } from '../types/api'

function label(value:string){return value.replaceAll('_',' ')}
function percent(value:number){return `${Math.round(value*100)}%`}

export function ResearcherDashboard({onBack}:{onBack:()=>void}) {
  const [data,setData]=useState<ResearchDashboardData>(),[error,setError]=useState(''),[downloading,setDownloading]=useState(false)
  useEffect(()=>{let active=true;void api.researchDashboard().then(value=>active&&setData(value)).catch(caught=>active&&setError(caught instanceof Error?caught.message:'Research data could not be loaded.'));return()=>{active=false}},[])
  async function download(){setDownloading(true);setError('');try{const blob=await api.researchCsv(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='affectlab-pilot-export.csv';link.click();URL.revokeObjectURL(url)}catch(caught){setError(caught instanceof Error?caught.message:'Export failed.')}finally{setDownloading(false)}}
  if(!data&&!error)return <main className="research-shell research-loading" role="status"><span className="loading-mark" aria-hidden="true">A</span><p>Preparing pseudonymous study metrics…</p></main>
  return <main className="research-shell"><header><button className="brand-link" onClick={onBack}><span className="brand-mark">A</span><span className="brand">AffectLab Research</span></button><button className="text-button" onClick={onBack}>← Participant dashboard</button></header>{error&&!data?<section className="research-error"><h1>Research dashboard unavailable.</h1><p role="alert">{error}</p><button className="primary" onClick={onBack}>Return</button></section>:data&&<>
    <section className="research-heading"><div><p className="eyebrow">Researcher view</p><h1>{data.study_label}</h1><p>Aggregate and pseudonymous pilot-study monitoring. Generated {new Date(data.generated_at).toLocaleString()}.</p></div><button className="primary" disabled={downloading} onClick={()=>void download()}>{downloading?'Preparing CSV…':'Export pseudonymous CSV'}</button></section>
    <section className="research-privacy" role="note"><strong>Privacy boundary</strong><span>No names, emails, conversation text, audio, or saved takeaways are available in this view or export.</span></section>
    {error&&<p className="error" role="alert">{error}</p>}
    <section className="research-kpis"><article><strong>{data.participants}</strong><span>enrolled participants</span></article><article><strong>{data.sessions}</strong><span>sessions created</span></article><article><strong>{data.completed_rehearsals}</strong><span>rehearsals completed</span></article><article><strong>{percent(data.completion_rate)}</strong><span>session completion rate</span></article></section>
    <div className="research-grid"><section className="research-card"><p className="eyebrow">Practice evidence</p><h2>Average skill scores</h2>{Object.keys(data.average_skill_scores).length?<div className="research-bars">{Object.entries(data.average_skill_scores).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><span><strong>{label(name)}</strong><small>{percent(value)}</small></span><i><b style={{width:percent(value)}}/></i></div>)}</div>:<p>No completed rehearsal evidence yet.</p>}</section>
      <section className="research-card"><p className="eyebrow">Study measures</p><h2>Questionnaire averages</h2>{Object.keys(data.questionnaire_averages).length?<dl className="research-measures">{Object.entries(data.questionnaire_averages).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value.toFixed(2)} / 7</dd></div>)}</dl>:<p>No questionnaire responses yet.</p>}</section>
      <section className="research-card"><p className="eyebrow">Coverage</p><h2>Completed scenarios</h2><dl className="research-measures">{Object.entries(data.scenario_completions).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value}</dd></div>)}</dl><h3>Difficulty</h3><dl className="research-measures compact">{Object.entries(data.difficulty_completions).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value}</dd></div>)}</dl></section>
      <section className="research-card"><p className="eyebrow">System behavior</p><h2>Feedback sources</h2><dl className="research-measures">{Object.entries(data.generation_sources).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value}</dd></div>)}</dl></section></div>
    <section className="participant-table"><div><p className="eyebrow">Pilot operations</p><h2>Participant activity</h2></div><div className="table-scroll"><table><thead><tr><th>Participant ID</th><th>Enrolled</th><th>Last active</th><th>Sessions</th><th>Completed</th><th>Pre / post forms</th></tr></thead><tbody>{data.participant_activity.map(item=><tr key={item.participant_id}><td><code>{item.participant_id.slice(0,8)}…</code></td><td>{new Date(item.enrolled_at).toLocaleDateString()}</td><td>{new Date(item.last_active_at).toLocaleDateString()}</td><td>{item.sessions}</td><td>{item.completed_rehearsals}</td><td>{item.pre_questionnaires} / {item.post_questionnaires}</td></tr>)}</tbody></table></div>{!data.participant_activity.length&&<p>No participants are enrolled yet.</p>}</section>
  </>}</main>
}
