import { useEffect, useState } from 'react'
import { api } from '../services/api'
import type { ResearchDashboardData } from '../types/api'

function label(value:string){return value.replaceAll('_',' ')}
function percent(value:number){return `${Math.round(value*100)}%`}

export function ResearcherDashboard({onBack}:{onBack:()=>void}) {
  const [data,setData]=useState<ResearchDashboardData>(),[error,setError]=useState(''),[downloading,setDownloading]=useState(false)
  const [startDate,setStartDate]=useState(''),[endDate,setEndDate]=useState(''),[busy,setBusy]=useState(false)
  async function refresh(){const value=await api.researchDashboard();setData(value);setStartDate(value.lifecycle.start_date??'');setEndDate(value.lifecycle.end_date??'')}
  useEffect(()=>{let active=true;void api.researchDashboard().then(value=>{if(active){setData(value);setStartDate(value.lifecycle.start_date??'');setEndDate(value.lifecycle.end_date??'')}}).catch(caught=>active&&setError(caught instanceof Error?caught.message:'Research data could not be loaded.'));return()=>{active=false}},[])
  async function download(){setDownloading(true);setError('');try{const blob=await api.researchCsv(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='affectlab-pilot-export.csv';link.click();URL.revokeObjectURL(url)}catch(caught){setError(caught instanceof Error?caught.message:'Export failed.')}finally{setDownloading(false)}}
  async function saveLifecycle(){setBusy(true);setError('');try{await api.updateResearchLifecycle(startDate,endDate);await refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Study dates could not be saved.')}finally{setBusy(false)}}
  async function freeze(){if(!confirm('Freeze this dataset permanently? Enrollment and research-data edits will be locked for this protocol version.'))return;setBusy(true);setError('');try{await api.freezeResearchDataset();await refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Dataset could not be frozen.')}finally{setBusy(false)}}
  async function reviewParticipant(item:ResearchDashboardData['participant_activity'][number]){if(item.withdrawn||data?.lifecycle.dataset_frozen_at)return;const note=prompt('Data-quality note (leave blank for none):',item.data_quality_notes);if(note===null)return;const exclusion=confirm(item.excluded?'Press OK to keep this participant excluded, or Cancel to include them.':'Press OK to exclude this participant from analysis, or Cancel to keep them included.');let reason=item.exclusion_reason;if(exclusion){const entered=prompt('Exclusion reason:',reason);if(entered===null||!entered.trim())return;reason=entered}setBusy(true);try{await api.updateParticipantResearch(item.participant_id,{excluded:exclusion,exclusion_reason:reason,data_quality_notes:note});await refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Participant review could not be saved.')}finally{setBusy(false)}}
  if(!data&&!error)return <main className="research-shell research-loading" role="status"><span className="loading-mark" aria-hidden="true">A</span><p>Preparing pseudonymous study metrics…</p></main>
  return <main className="research-shell"><header><button className="brand-link" onClick={onBack}><span className="brand-mark">A</span><span className="brand">AffectLab Research</span></button><button className="text-button" onClick={onBack}>← Participant dashboard</button></header>{error&&!data?<section className="research-error"><h1>Research dashboard unavailable.</h1><p role="alert">{error}</p><button className="primary" onClick={onBack}>Return</button></section>:data&&<>
    <section className="research-heading"><div><p className="eyebrow">Researcher view · {data.protocol_version}</p><h1>{data.study_label}</h1><p>Aggregate and pseudonymous pilot-study monitoring. Generated {new Date(data.generated_at).toLocaleString()}.</p></div><button className="primary" disabled={downloading} onClick={()=>void download()}>{downloading?'Preparing CSV…':'Export pseudonymous CSV'}</button></section>
    <section className="research-privacy" role="note"><strong>Privacy boundary</strong><span>No names, emails, conversation text, audio, or saved takeaways are available in this view or export.</span></section>
    {error&&<p className="error" role="alert">{error}</p>}
    <section className="research-card lifecycle-card"><p className="eyebrow">Study lifecycle</p><h2>{data.lifecycle.dataset_frozen_at?'Dataset frozen':'Collection controls'}</h2><div className="lifecycle-fields"><label>Study start<input type="date" value={startDate} disabled={Boolean(data.lifecycle.dataset_frozen_at)} onChange={event=>setStartDate(event.target.value)}/></label><label>Study end<input type="date" value={endDate} disabled={Boolean(data.lifecycle.dataset_frozen_at)} onChange={event=>setEndDate(event.target.value)}/></label></div>{data.frozen_export?<dl className="freeze-manifest"><div><dt>Frozen</dt><dd>{new Date(data.frozen_export.created_at).toLocaleString()}</dd></div><div><dt>Schema</dt><dd>{data.frozen_export.schema_version}</dd></div><div><dt>Records</dt><dd>{data.frozen_export.record_count}</dd></div><div><dt>Participants</dt><dd>{data.frozen_export.participant_count}</dd></div><div className="wide"><dt>SHA-256</dt><dd><code>{data.frozen_export.sha256}</code></dd></div></dl>:<div className="lifecycle-actions"><button className="secondary" disabled={busy||!startDate||!endDate} onClick={()=>void saveLifecycle()}>Save study dates</button><button className="danger-button" disabled={busy||!startDate||!endDate} onClick={()=>void freeze()}>Freeze final dataset</button></div>}<p className="privacy-summary">Freezing creates an immutable de-identified CSV with new analysis IDs and no stored identity lookup. This action cannot be undone for the current protocol version.</p></section>
    <section className="research-kpis"><article><strong>{data.participants} / {data.participant_target}</strong><span>enrolled participant target</span></article><article><strong>{data.protocol_completers} / {data.completer_target}</strong><span>protocol completer target</span></article><article><strong>{data.completed_rehearsals}</strong><span>rehearsals completed</span></article><article><strong>{percent(data.protocol_completion_rate)}</strong><span>protocol completion rate</span></article></section>
    <div className="research-grid"><section className="research-card"><p className="eyebrow">Practice evidence</p><h2>Average skill scores</h2>{Object.keys(data.average_skill_scores).length?<div className="research-bars">{Object.entries(data.average_skill_scores).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><span><strong>{label(name)}</strong><small>{percent(value)}</small></span><i><b style={{width:percent(value)}}/></i></div>)}</div>:<p>No completed rehearsal evidence yet.</p>}</section>
      <section className="research-card"><p className="eyebrow">Study measures</p><h2>Questionnaire averages</h2>{Object.keys(data.questionnaire_averages).length?<dl className="research-measures">{Object.entries(data.questionnaire_averages).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value.toFixed(2)} / 7</dd></div>)}</dl>:<p>No questionnaire responses yet.</p>}</section>
      <section className="research-card"><p className="eyebrow">Coverage</p><h2>Completed scenarios</h2><dl className="research-measures">{Object.entries(data.scenario_completions).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value}</dd></div>)}</dl><h3>Difficulty</h3><dl className="research-measures compact">{Object.entries(data.difficulty_completions).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value}</dd></div>)}</dl></section>
      <section className="research-card"><p className="eyebrow">System behavior</p><h2>Feedback sources</h2><dl className="research-measures">{Object.entries(data.generation_sources).map(([name,value])=><div key={name}><dt>{label(name)}</dt><dd>{value}</dd></div>)}</dl></section></div>
    <section className="participant-table"><div><p className="eyebrow">Pilot operations</p><h2>Participant activity</h2></div><div className="table-scroll"><table><thead><tr><th>Participant ID</th><th>Enrolled</th><th>Last active</th><th>Records</th><th>Rehearsals</th><th>Status</th><th>Pre / post</th><th>Review</th></tr></thead><tbody>{data.participant_activity.map(item=><tr key={item.participant_id} className={item.excluded||item.withdrawn?'flagged-participant':''}><td><code>{item.participant_id.slice(0,8)}…</code></td><td>{new Date(item.enrolled_at).toLocaleDateString()}</td><td>{new Date(item.last_active_at).toLocaleDateString()}</td><td>{item.sessions}</td><td>{item.completed_rehearsals}</td><td><span className={`research-status ${item.completion_status}`}>{label(item.completion_status)}</span></td><td>{item.pre_questionnaires} / {item.post_questionnaires}</td><td><button className="text-button" disabled={busy||item.withdrawn||Boolean(data.lifecycle.dataset_frozen_at)} title={item.data_quality_notes||item.exclusion_reason||''} onClick={()=>void reviewParticipant(item)}>Review</button></td></tr>)}</tbody></table></div>{!data.participant_activity.length&&<p>No participants are enrolled yet.</p>}</section>
  </>}</main>
}
