import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { api } from '../services/api'
import type { SessionSummary, StudyInformation, UserProfile } from '../types/api'
import { PRACTICE_GOALS } from '../practiceGoals'

export function SettingsPage({user, onUser, onBack, onSignedOut}: {user: UserProfile; onUser: (user: UserProfile) => void; onBack: () => void; onSignedOut: () => void}) {
  const [profile, setProfile] = useState({first_name:user.first_name, last_name:user.last_name, preferred_name:user.preferred_name, country:user.country, timezone:user.timezone})
  const [sessions, setSessions] = useState<SessionSummary[]>([])
  const [microphone, setMicrophone] = useState(localStorage.getItem('affectlab_microphone_enabled') !== 'false')
  const [goals, setGoals] = useState<string[]>(user.practice_goals)
  const [currentPassword, setCurrentPassword] = useState(''), [newPassword, setNewPassword] = useState(''), [confirmPassword, setConfirmPassword] = useState('')
  const [profileMessage, setProfileMessage] = useState(''), [passwordMessage, setPasswordMessage] = useState(''), [busy, setBusy] = useState(false)

  useEffect(() => {
    let active=true
    void api.listSessions().then(value=>active&&setSessions(value))
    return()=>{active=false}
  }, [])
  function field(name: keyof typeof profile, value: string) { setProfile(previous => ({...previous, [name]:value})) }
  async function saveProfile(event: FormEvent) { event.preventDefault(); setBusy(true); setProfileMessage(''); try { const updated = await api.updateProfile(profile); onUser(updated); setProfileMessage('Profile saved.') } catch (caught) { setProfileMessage(caught instanceof Error ? caught.message : 'Profile could not be saved.') } finally { setBusy(false) } }
  async function changePassword(event: FormEvent) {
    event.preventDefault(); setPasswordMessage('')
    if (newPassword !== confirmPassword) { setPasswordMessage('New passwords do not match.'); return }
    setBusy(true)
    try { await api.changePassword(currentPassword, newPassword); api.clearToken(); onSignedOut() }
    catch (caught) { setPasswordMessage(caught instanceof Error ? caught.message : 'Password could not be changed.') } finally { setBusy(false) }
  }
  function setMicrophonePreference(value: boolean) { setMicrophone(value); localStorage.setItem('affectlab_microphone_enabled', String(value)) }
  function toggleGoal(id:string) { setGoals(current => current.includes(id) ? current.filter(goal => goal !== id) : current.length < 3 ? [...current,id] : current) }
  async function saveGoals() { if (!goals.length) { setProfileMessage('Choose at least one practice goal.'); return } setBusy(true); setProfileMessage(''); try { onUser(await api.completeOnboarding(goals)); setProfileMessage('Practice goals saved.') } catch (caught) { setProfileMessage(caught instanceof Error ? caught.message : 'Goals could not be saved.') } finally { setBusy(false) } }
  async function removeSession(id: string) { if (!confirm('Delete this session permanently?')) return; await api.deleteSession(id); setSessions(current => current.filter(session => session.session_id !== id)) }
  async function downloadResearchData() {
    const data = await api.researchExport()
    const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], {type:'application/json'}))
    const link = document.createElement('a'); link.href = url; link.download = `affectlab-research-${data.participant_id}.json`; link.click()
    URL.revokeObjectURL(url)
  }

  return <main className="settings-shell">
    <header><button className="brand-link" onClick={onBack}><span className="brand-mark">A</span><span className="brand">AffectLab</span></button><button className="text-button" onClick={onBack}>← Back to workspace</button></header>
    <section className="settings-heading"><p className="eyebrow">Account settings</p><h1>Your profile and privacy.</h1><p>Manage personal details, voice preferences, saved sessions, and account security.</p></section>
    <div className="settings-grid">
      <section className="settings-card"><p className="eyebrow">Profile</p><h2>Personal details</h2><form className="settings-form" onSubmit={saveProfile}><div className="form-row"><label>First name<input value={profile.first_name} onChange={event => field('first_name',event.target.value)} required maxLength={80}/></label><label>Last name<input value={profile.last_name} onChange={event => field('last_name',event.target.value)} required maxLength={80}/></label></div><label>Preferred name<input value={profile.preferred_name} onChange={event => field('preferred_name',event.target.value)} maxLength={80}/></label><label>Email<input value={user.email} disabled/><small>Email changes require a separate confirmation flow and are not currently available.</small></label><div className="form-row"><label>Country<input value={profile.country} onChange={event => field('country',event.target.value)} maxLength={80}/></label><label>Timezone<input value={profile.timezone} onChange={event => field('timezone',event.target.value)} required maxLength={80}/></label></div>{profileMessage && <p className="settings-message" role="status">{profileMessage}</p>}<button className="primary" disabled={busy}>Save profile</button></form></section>
      <section className="settings-card"><p className="eyebrow">Voice and privacy</p><h2>Microphone preference</h2><label className="preference-row"><span><strong>Enable optional voice input</strong><small>Recording still starts only when you press Add voice.</small></span><input type="checkbox" checked={microphone} onChange={event => setMicrophonePreference(event.target.checked)}/></label><div className="privacy-summary"><p>Text may be stored locally for up to 30 days and sent to OpenAI when configured.</p><p>Optional audio may be sent to OpenAI for transcription and processed locally for affect inference. AffectLab does not persist recordings.</p><p>Emotion estimates are uncertain and are not diagnoses.</p></div></section>
      <section className="settings-card settings-goals"><p className="eyebrow">Personal practice</p><h2>Your goals</h2><p className="privacy-summary">Choose one to three. These shape your recommended starting scenario, but never restrict what you can practise.</p><div className="goal-grid compact">{PRACTICE_GOALS.map(goal=><button key={goal.id} className={goals.includes(goal.id)?'selected':''} aria-pressed={goals.includes(goal.id)} onClick={()=>toggleGoal(goal.id)}><span>{goals.includes(goal.id)?'✓':'+'}</span><div><strong>{goal.label}</strong></div></button>)}</div><button className="primary" disabled={busy||!goals.length} onClick={()=>void saveGoals()}>Save goals</button></section>
      <section className="settings-card"><p className="eyebrow">Research record</p><h2>Export pseudonymous data</h2><p className="privacy-summary">Download your consent record, questionnaire ratings, interaction events, and feedback metrics. The export excludes your email, name, password data, and conversation text.</p><button className="secondary" onClick={() => void downloadResearchData()}>Download research JSON</button></section>
      <StudyParticipationCard user={user} onUser={onUser}/>
      <section className="settings-card"><p className="eyebrow">Security</p><h2>Change password</h2><form className="settings-form" onSubmit={changePassword}><label>Current password<input type="password" autoComplete="current-password" minLength={10} value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} required/></label><label>New password<input type="password" autoComplete="new-password" minLength={10} value={newPassword} onChange={event => setNewPassword(event.target.value)} required/></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={10} value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} required/></label>{passwordMessage && <p className="settings-message error" role="alert">{passwordMessage}</p>}<button className="primary" disabled={busy}>Change password and sign out</button></form></section>
      <section className="settings-card sessions-settings"><p className="eyebrow">Stored locally</p><h2>Sessions</h2>{sessions.length ? <div className="settings-session-list">{sessions.map((session,index) => <article key={session.session_id}><div><strong>Session {sessions.length-index}</strong><small>{new Date(session.updated_at).toLocaleString()} · {session.turn_count} turns{session.roleplay ? ` · ${session.roleplay.scenario_id}` : ''}</small></div><button onClick={() => removeSession(session.session_id)}>Delete</button></article>)}</div> : <p>No active sessions are stored.</p>}</section>
      <section className="settings-card danger-zone"><p className="eyebrow">Danger zone</p><h2>Delete account</h2><p>This permanently removes the account, saved sessions, and refresh tokens.</p><button onClick={async () => { if (confirm('Permanently delete your AffectLab account and every session?')) { await api.deleteAccount(); onSignedOut() } }}>Delete my account</button></section>
    </div>
  </main>
}

function StudySection({title,items}:{title:string;items:string[]}) { return <section><h4>{title}</h4><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></section> }

function StudyParticipationCard({user,onUser}:{user:UserProfile;onUser:(user:UserProfile)=>void}) {
  const [info,setInfo]=useState<StudyInformation>(),[error,setError]=useState(''),[message,setMessage]=useState('')
  const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[confirming,setConfirming]=useState(false),[withdrawalAcknowledged,setWithdrawalAcknowledged]=useState(false)
  const [checks,setChecks]=useState({read:false,participate:false,data:false})
  useEffect(()=>{if(user.pilot_enrolled||user.study_withdrawn)return;let active=true;void api.studyInformation().then(value=>active&&setInfo(value)).catch(caught=>active&&setError(caught instanceof Error?caught.message:'Study information could not be loaded.'));return()=>{active=false}},[user.pilot_enrolled,user.study_withdrawn])
  async function enroll(event:FormEvent){event.preventDefault();if(!info)return;setBusy(true);setError('');try{onUser(await api.enrollPilot({access_code:code,consent_version:info.version,information_sheet_read:checks.read,research_participation_accepted:checks.participate,data_processing_accepted:checks.data}));setMessage('Pilot enrollment completed.')}catch(caught){setError(caught instanceof Error?caught.message:'Enrollment failed.')}finally{setBusy(false)}}
  async function withdraw(){setBusy(true);setError('');try{const result=await api.withdrawFromStudy();onUser(result.user);setMessage(`${result.message} ${result.anonymized_analysis_notice}`)}catch(caught){setError(caught instanceof Error?caught.message:'Withdrawal could not be completed.')}finally{setBusy(false)}}
  if(user.study_withdrawn)return <section className="settings-card study-consent-card withdrawn-study"><p className="eyebrow">Pilot study</p><h2>You withdrew from the study</h2><p className="privacy-summary">Your account remains active, but it is excluded from future researcher dashboards and exports. Eligible questionnaires and research-event telemetry held by AffectLab were deleted.</p><dl className="consent-record"><div><dt>Withdrawal recorded</dt><dd>{user.study_withdrawn_at?new Date(user.study_withdrawn_at).toLocaleString():'Recorded'}</dd></div><div><dt>Account access</dt><dd>Unaffected</dd></div></dl><p className="withdrawal-notice">Data already irreversibly anonymised or included in completed aggregate analysis may no longer be identifiable and therefore may not be removable.</p>{message&&<p className="settings-message" role="status">{message}</p>}</section>
  if(user.pilot_enrolled)return <section className="settings-card study-consent-card"><p className="eyebrow">Pilot study</p><h2>You are enrolled</h2><p className="privacy-summary">Your research consent is separate from your AffectLab account. Your pseudonymous participant ID is used in researcher exports; names, email, conversation text, voice recordings, and saved takeaways are excluded.</p><dl className="consent-record"><div><dt>Consent version</dt><dd>{user.study_consent_version}</dd></div><div><dt>Accepted</dt><dd>{user.study_consented_at?new Date(user.study_consented_at).toLocaleString():'Recorded'}</dd></div></dl><code className="participant-code">{user.participant_id}</code><div className="withdrawal-panel"><h3>Withdraw from the pilot study</h3><p>This keeps your account and ordinary practice data, removes eligible study questionnaires and research-event telemetry, and excludes you from future research exports.</p>{confirming?<><label className="consent"><input type="checkbox" onChange={event=>setWithdrawalAcknowledged(event.target.checked)} checked={withdrawalAcknowledged}/><span>I understand that withdrawal cannot remove data already irreversibly anonymised or included in completed aggregate analysis.</span></label><div className="withdrawal-actions"><button className="text-button" onClick={()=>{setConfirming(false);setWithdrawalAcknowledged(false)}}>Cancel</button><button className="danger-button" disabled={busy||!withdrawalAcknowledged} onClick={()=>void withdraw()}>{busy?'Withdrawing…':'Confirm study withdrawal'}</button></div></>:<button className="danger-button" onClick={()=>setConfirming(true)}>Withdraw from study</button>}{error&&<p className="settings-message error" role="alert">{error}</p>}</div></section>
  return <section className="settings-card study-consent-card"><p className="eyebrow">Pilot study</p><h2>Participant information and consent</h2>{info?<><div className="study-sheet" aria-labelledby="study-sheet-title"><div className="study-sheet-heading"><span>Version {info.version}</span><h3 id="study-sheet-title">{info.title}</h3><p>{info.summary}</p></div><StudySection title="What data is collected" items={info.data_collected}/><StudySection title="Services and data processors" items={info.processors}/><StudySection title="Audio and transcripts" items={info.audio_and_transcripts}/><section><h4>Retention period</h4><p>{info.retention}</p></section><StudySection title="Risks and limitations" items={info.risks_and_limitations}/><StudySection title="Your right to withdraw" items={info.withdrawal}/><section><h4>Study contacts</h4><p><strong>Researcher:</strong> {info.researcher.name} · {info.researcher.email}<br/><strong>Supervisor:</strong> {info.supervisor.name} · {info.supervisor.email}<br/><strong>Institution:</strong> {info.institution}</p></section></div><form className="settings-form study-consent-form" onSubmit={enroll}><label>Study access code<input value={code} onChange={event=>setCode(event.target.value)} autoComplete="off" required/></label><label className="consent"><input type="checkbox" checked={checks.read} onChange={event=>setChecks(value=>({...value,read:event.target.checked}))} required/><span>I have read and understood participant information version {info.version} and had the opportunity to ask questions.</span></label><label className="consent"><input type="checkbox" checked={checks.participate} onChange={event=>setChecks(value=>({...value,participate:event.target.checked}))} required/><span>I voluntarily agree to participate and understand I can stop without giving a reason.</span></label><label className="consent"><input type="checkbox" checked={checks.data} onChange={event=>setChecks(value=>({...value,data:event.target.checked}))} required/><span>I agree to the processing described above, including possible OpenAI processing and optional audio handling.</span></label>{error&&<p className="settings-message error" role="alert">{error}</p>}<button className="primary" disabled={busy||!checks.read||!checks.participate||!checks.data}>{busy?'Recording consent…':'Consent and join pilot study'}</button></form></>:<p className="settings-message error" role="alert">{error||'Loading participant information…'}</p>}</section>
}
