export type Role = 'user' | 'assistant'
export interface EmotionState { dominant_emotion: string; valence: number; arousal: number; confidence: number; trend: string }
export interface ConversationTurn { id: string; role: Role; content: string; created_at: string }
export interface RolePlayState { scenario_id: string; scenario?: Scenario | null; status: string; difficulty_level: string; turn: number; success_progress: number; completion_reason?: string | null }
export interface Feedback { session_id?: string|null; scenario_id: string; observed: string[]; strengths: string[]; suggestions: string[]; generation_source: string; metrics: { name: string; score: number; evidence_turns?: number[] }[]; compared_with_session_id?:string|null; comparisons:{name:string;current_score:number;previous_score:number;change:number}[] }
export interface ChatResponse { turn: ConversationTurn; decision: { emotion_state: EmotionState; strategy: string; cognitive_assessment: { possible_distortion: string|null; possible_cause: string|null; intent: string }; decision_reasons: string[]; analyzer_version: string }; roleplay: RolePlayState | null; feedback: Feedback | null }
export interface Scenario { id: string; title: string; character: string; situation?: string; user_objective: string; opening_line?: string; expected_skills: string[] }
export interface SessionResponse { session_id: string; title: string; turns: ConversationTurn[]; emotion_state: EmotionState; roleplay: RolePlayState | null; feedback: Feedback | null; takeaway:string }
export interface SessionSummary { session_id: string; title: string; created_at: string; updated_at: string; turn_count: number; roleplay?: RolePlayState | null; feedback?: Feedback | null; takeaway:string }
export interface UserProfile { id: string; email: string; first_name: string; last_name: string; preferred_name: string; country: string; timezone: string; email_verified: boolean; practice_goals: string[]; onboarding_completed: boolean; onboarding_version?: string | null; researcher:boolean; pilot_enrolled:boolean; study_consent_version?:string|null; study_consented_at?:string|null; study_withdrawn:boolean; study_withdrawn_at?:string|null; participant_id:string }
export interface StudyWithdrawal { user:UserProfile; questionnaires_deleted:number; research_events_deleted:number; message:string; anonymized_analysis_notice:string }
export interface StudyContact { name:string; email:string }
export interface StudyInformation { version:string; protocol_version:string; study_label:string; title:string; summary:string; data_collected:string[]; processors:string[]; audio_and_transcripts:string[]; retention:string; risks_and_limitations:string[]; withdrawal:string[]; researcher:StudyContact; supervisor:StudyContact; institution:string }
export interface ModelInfo { trained_model: boolean; multimodal_model: string | null; multimodal_status: string; transcription_available: boolean; transcription_model: string | null; disclaimer: string }
export interface MultimodalAffect { label: string; confidence: number; distribution: Record<string,number>; text_label: string; text_confidence: number; text_distribution: Record<string,number>; audio_label: string; audio_confidence: number; audio_distribution: Record<string,number>; modalities_agree: boolean; confidence_level: 'low'|'moderate'|'high'; low_confidence_threshold: number; model_version: string; latency_ms: number; queue_ms: number; audio_persisted: false; disclaimer: string }
export interface AudioTranscription { text: string; model: string; latency_ms: number; audio_persisted: false }
export interface StudyQuestionnaire { phase: 'pre'|'post'; confidence?: number|null; anxiety?: number|null; realism?: number|null; usefulness?: number|null; submitted_at: string }
export interface ResearchExport { schema_version: string; protocol_version:string; participant_id: string; contains_conversation_text: false; account_privacy_acceptance: {version:string;accepted_at:string}; study_consent: {version:string;protocol_version:string;accepted_at:string}|null; study_withdrawal:{withdrawn_at:string;consent_version:string;data_action:string}|null; records: unknown[] }
export interface ResearchDashboardData { study_label:string; protocol_version:string; generated_at:string; participants:number; participant_target:number; sessions:number; completed_rehearsals:number; completion_rate:number; protocol_completers:number; completer_target:number; protocol_completion_rate:number; scenario_completions:Record<string,number>; difficulty_completions:Record<string,number>; average_skill_scores:Record<string,number>; questionnaire_averages:Record<string,number>; generation_sources:Record<string,number>; lifecycle:{protocol_version:string;start_date?:string|null;end_date?:string|null;dataset_frozen_at?:string|null;frozen_export_id?:string|null}; frozen_export:{export_id:string;schema_version:string;created_at:string;record_count:number;participant_count:number;sha256:string}|null; participant_activity:{participant_id:string;enrolled_at:string;last_active_at:string;sessions:number;completed_rehearsals:number;protocol_complete:boolean;completion_status:string;excluded:boolean;withdrawn:boolean;exclusion_reason:string;data_quality_notes:string;pre_questionnaires:number;post_questionnaires:number}[]; privacy:{contains_names:false;contains_emails:false;contains_conversation_text:false;contains_takeaways:false} }
